# Generated by Django 4.2.3 on 2023-07-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medieval', '0002_remove_king_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
    ]
