# Generated by Django 4.2.3 on 2023-07-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medieval', '0003_remove_person_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='God',
        ),
    ]
