# Generated by Django 4.2.3 on 2023-07-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medieval', '0004_rename_category_god'),
    ]

    operations = [
        migrations.DeleteModel(
            name='God',
        ),
    ]
