# Generated by Django 4.2.3 on 2023-07-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medieval', '0005_delete_god'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='categoryType',
            field=models.CharField(choices=[('Боярин', 'Бояре'), ('Дворянин', 'Дворяне')], default='Боярин'),
        ),
    ]
