# Generated by Django 4.2.3 on 2023-07-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medieval', '0008_servant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Добавить Боярина или Дворянина'},
        ),
    ]
