# Generated by Django 4.2.3 on 2023-07-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medieval', '0012_remove_servant_name_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cash',
            field=models.CharField(max_length=256, verbose_name='Зарплата(золотых)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='categoryType',
            field=models.CharField(choices=[('Боярин', 'Бояре'), ('Дворянин', 'Дворяне')], default='Боярин', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=256, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(max_length=256, verbose_name='Возраст'),
        ),
    ]
