# Generated by Django 4.2.3 on 2023-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medieval', '0013_alter_person_cash_alter_person_categorytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Имя Фамилия'),
        ),
        migrations.AlterField(
            model_name='servant',
            name='cash',
            field=models.CharField(max_length=256, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='servant',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Имя фамилия'),
        ),
        migrations.AlterField(
            model_name='servant',
            name='year',
            field=models.CharField(max_length=256, verbose_name='Возраст'),
        ),
    ]
