# Generated by Django 4.2.3 on 2023-07-29 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medieval', '0014_alter_person_name_alter_servant_cash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='king',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Король'),
        ),
        migrations.AlterField(
            model_name='servant',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medieval.person', verbose_name='Относится к:'),
        ),
    ]
