# Generated by Django 4.2.3 on 2023-07-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medieval', '0015_alter_king_user_alter_servant_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedieVallPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='indexpage',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='Обо мне'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='name',
            field=models.CharField(blank=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='projects',
            field=models.TextField(blank=True, verbose_name='Проекты'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='work_experiens',
            field=models.TextField(blank=True, verbose_name='Опыт работы'),
        ),
    ]
