# Generated by Django 4.2.3 on 2023-07-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medieval', '0016_medievallpage_indexpage_about_me_indexpage_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name_plural': 'Резюме'},
        ),
    ]
